baseURL = 'https://laurenhendriks.nl/'
locale = 'nl'
title = 'Lauren Hendriks'
theme = 'laurenhendriks'

[params]
  description = 'Orthomoleculair therapeut | voeding · gezondheid · leefstijl'
  formspreeEndpoint = 'https://formspree.io/f/mbdewjlp'
  hasPhoto = false
